<div class="content-header">
    <h3><?php echo $this->__('Recommended Extensions') ?></h3>
    <p class="form-buttons"></p>
</div>

<div class="entry-edit">
	<div class="entry-edit-head">
    	<h4 class="icon-head head-edit-form fieldset-legend"><?php echo $this->__('Recommended Extensions') ?></h4>
        <div class="form-buttons"></div>
    </div>
    <div class="fieldset fieldset-wide" id="group_fields7">
		<div class="hor-scroll">
    		<table cellspacing="0" class="form-list">
        		<tbody>
<?php /** @JDS TODO add countries */ ?>
                    <tr><td class="value" colspan="2"><strong><?php echo $this->__('Language package') ?></strong></td></tr>
                    <tr>
                    	<td class="label"><label for="name">MagentoConnect</label></td>
                    	<td class="value"><a href="http://www.magentocommerce.com/extension/123456/" target="_blank">http://www.magentocommerce.com/extension/123456/</a></td>
                    </tr>
				</tbody>
    		</table>
		</div>
	</div>
</div>

<div class="entry-edit">
	<div class="entry-edit-head">
    	<h4 class="icon-head head-edit-form fieldset-legend"><?php echo $this->__('Popular Payment Methods in Germany') ?></h4>
        <div class="form-buttons"></div>
    </div>
    <div class="fieldset fieldset-wide" id="group_fields7">
		<div class="hor-scroll">
    		<table cellspacing="0" class="form-list">
        		<tbody>
<?php /** @JDS TODO add payment modules */ ?>
        		</tbody>
    		</table>
		</div>
	</div>
</div>
