<?php /** @var $this Mdp2012_Localiser_Block_Adminhtml_Notifications */ ?>
<?php if (!$this->isInitialized()): ?>
<div class="notification-global">
    <strong><?php echo $this->helper('localiser')->__('Localiser has been installed.') ?></strong>
    <?php echo $this->helper('localiser')->__('Click <a href="%s">here</a> to set up your pages, blocks, emails and tax settings.', $this->getManageUrl()) ?>
</div>
<?php endif ?>
